version: '3.8'

services:
    ingestion-service:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "80:80"
        environment:
            USERNAME: admin
            PASSWORD: admin
        volumes:
            - ./data/:/app/data/
        restart: always